config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :sessions, only: [:create]
  resources :users, only: [:show, :new, :create]
  resources :deals, only: [:index]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true


  def full_name
    self.first_name.capitalize + ' ' + self.last_name.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to deals_path
    else
      redirect_to root_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to deals_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deals/index.html.erb
<%= react_component('Main', {
  user: current_user.full_name
  }) %>

app/views/home/index.html.erb
<div>
  <%= form_for :session, url: sessions_path do |f| %>
    <%= f.text_field :email, placeholder: 'Email' %>
    <br>
    <%= f.text_field :password, placeholder: 'Password' %>
    <br>
    <%= f.submit 'Sign In' %>
  <% end %>
  <br>
  <%= link_to 'Sign Up', new_user_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactFun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div>
  <%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit 'Create Account' %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= @user.first_name %>
<%= @user.last_name %>